# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b064f095f49dfe8bb5bdeea0de5e0a9deab5be1121567634c99d53c435f66e85b5db798c24a0efbc8e4f507cc6c83137ef1b95f5d35f9f1416406ecc4aa4c1c1

test:
  secret_key_base: 8cc9e2cb956edd4e5258be1653a403479b74c6ddf31fb076a32e9998420cb3f25502394e27b716de29d5fa65e51553f87364425bfdc62c0b65d97a400b383c5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
